//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.11 at 12:47:48 PM BRST 
//


package br.com.soaexpert.ged.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Documento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Documento">
 *   &lt;complexContent>
 *     &lt;extension base="{http://services.soaexpert.com.br/AccessControl}Recurso">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipo" type="{http://services.soaexpert.com.br/GEDSOA/Documento}MediaType"/>
 *         &lt;element name="versao" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="binario" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Documento", namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", propOrder = {
    "id",
    "nome",
    "descricao",
    "tipo",
    "versao",
    "binario",
    "tag"
})
public class Documento
    extends Recurso implements Entity
{

    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento")
    protected long id;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", required = true)
    protected String nome;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", required = true)
    protected String descricao;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", required = true)
    protected String tipo;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento")
    protected int versao;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", required = true)
    protected byte[] binario;
    @XmlElement(namespace = "http://services.soaexpert.com.br/GEDSOA/Documento", required = true)
    protected List<String> tag;

    /**
     * Gets the value of the id property.
     * 
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the versao property.
     * 
     */
    public int getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     */
    public void setVersao(int value) {
        this.versao = value;
    }

    /**
     * Gets the value of the binario property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBinario() {
        return binario;
    }

    /**
     * Sets the value of the binario property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBinario(byte[] value) {
        this.binario = ((byte[]) value);
    }

    /**
     * Gets the value of the tag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTag() {
        if (tag == null) {
            tag = new ArrayList<String>();
        }
        return this.tag;
    }

}
