//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.11 at 12:47:48 PM BRST 
//


package br.com.soaexpert.ged.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for TipoAcesso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipoAcesso">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leitura"/>
 *     &lt;enumeration value="inclusao"/>
 *     &lt;enumeration value="alteracao"/>
 *     &lt;enumeration value="exclusao"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum TipoAcesso {

    @XmlEnumValue("alteracao")
    ALTERACAO("alteracao"),
    @XmlEnumValue("exclusao")
    EXCLUSAO("exclusao"),
    @XmlEnumValue("inclusao")
    INCLUSAO("inclusao"),
    @XmlEnumValue("leitura")
    LEITURA("leitura");
    private final String value;

    TipoAcesso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TipoAcesso fromValue(String v) {
        for (TipoAcesso c: TipoAcesso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
